# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nvidia/jetson/setup-makefiles.sh

PRODUCT_COPY_FILES += \
vendor/nvidia/jetson/proprietary/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
vendor/nvidia/jetson/proprietary/system/etc/firmware/ar3k/ramps_0x11020000_40.dfu:system/etc/firmware/ar3k/ramps_0x11020000_40.dfu \
vendor/nvidia/jetson/proprietary/system/etc/firmware/ar3k/AthrBT_0x11020000.dfu:system/etc/firmware/ar3k/AthrBT_0x11020000.dfu \
vendor/nvidia/jetson/proprietary/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
vendor/nvidia/jetson/proprietary/system/lib/libremotecontrolservice.so:system/lib/libremotecontrolservice.so \
vendor/nvidia/jetson/proprietary/system/priv-app/AtvRemoteService/lib/arm/libatv_uinputbridge.so:system/priv-app/AtvRemoteService/lib/arm/libatv_uinputbridge.so
